name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup variables
        run: echo "PUBLIC_IP=20.211.46.201" >> $GITHUB_ENV
        
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Create directory on Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no -l serveradmin  ${{ secrets.AZURE_SSH_PRIVATE_KEY }} username@${{ env.PUBLIC_IP }} << 'EOF'
            mkdir -p /feedgenerator
          EOF
          
      - name: Deploy build to Azure VM
        run: |
          scp -i ${{ secrets.AZURE_SSH_PRIVATE_KEY }} -r ./dist username@${{ env.PUBLIC_IP }}:/feedgenerator/
      
      - name: Run commands on Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.AZURE_SSH_PRIVATE_KEY }} username@${{ env.PUBLIC_IP }} << 'EOF'
            sudo apt update
            sudo apt install -y nodejs npm
            cd /feedgenerator
            node.exe ./index.js
          EOF