name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup variables
        run: echo "PUBLIC_IP=20.211.46.201" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Write SSH private key to a file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy repository to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa serveradmin@${{ env.PUBLIC_IP }} << 'EOF'
            # Update and install dependencies
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
            source ~/.bashrc
            nvm install v20.16.0

            sudo apt update
            sudo apt install -y npm yarn git

            # Clone the repository
            if [ -d "/feedgenerator" ]; then
              sudo rm -rf /feedgenerator
            fi
            sudo git clone https://github.com/${{ github.repository }} /feedgenerator

            # Change ownership to the current user
            sudo chown -R serveradmin:serveradmin /feedgenerator

            # Install and start the application
            cd /feedgenerator
            yarn install
            yarn start
          EOF